mutation {
  addSignatory(
    input: {
      signatureOrderId: "[signatureOrder.id]"
      documents: [
        {id: "[signatureOrder.documents[0].id]", preapproved: true}
        {id: "[signatureOrder.documents[1].id]", preapproved: true}
      ]
    }
  ) {
    signatory {
      href
    }
  }
}