mutation ($signatureOrderId : String!) {
  closeSignatureOrder(
    input: {
      signatureOrderId: $signatureOrderId
    }
  ) {
    signatureOrder {
      status

      documents {
        blob
      }
    }
  }
}