mutation ($docTitle : String!, $documentAsBase64 : String!) {
  createSignatureOrder(input: {
    documents:[{
      pdf: {
        title: $docTitle
        storageMode: Temporary
        blob: $documentAsBase64
      }
    }]}) {
    signatureOrder {
      id

      documents {
        id
      }
    }
  }
}