goog.provide('cljs_re_frame.db');
cljs_re_frame.db.generate_random_balance = (function cljs_re_frame$db$generate_random_balance(){
return (cljs.core.rand_int((1000000)) / (100));
});
cljs_re_frame.db.generate_random_date = (function cljs_re_frame$db$generate_random_date(){
return (new Date((2021),((1) + cljs.core.rand_int((12))),((1) + cljs.core.rand_int((28)))));
});
cljs_re_frame.db.default_db = new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"nav","nav",719540477),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"active-page","active-page",370357330),new cljs.core.Keyword(null,"front-page","front-page",-663760939)], null),new cljs.core.Keyword(null,"accounts","accounts",-935308676),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"account-name","account-name",-296718226),"Checking",new cljs.core.Keyword(null,"id","id",-1388402092),cljs.core.random_uuid(),new cljs.core.Keyword(null,"balance","balance",418967409),cljs_re_frame.db.generate_random_balance(),new cljs.core.Keyword(null,"last-transaction-date","last-transaction-date",-996917074),cljs_re_frame.db.generate_random_date()], null),new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"account-name","account-name",-296718226),"Savings",new cljs.core.Keyword(null,"id","id",-1388402092),cljs.core.random_uuid(),new cljs.core.Keyword(null,"balance","balance",418967409),cljs_re_frame.db.generate_random_balance(),new cljs.core.Keyword(null,"last-transaction-date","last-transaction-date",-996917074),cljs_re_frame.db.generate_random_date()], null),new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"account-name","account-name",-296718226),"Child savings",new cljs.core.Keyword(null,"id","id",-1388402092),cljs.core.random_uuid(),new cljs.core.Keyword(null,"balance","balance",418967409),cljs_re_frame.db.generate_random_balance(),new cljs.core.Keyword(null,"last-transaction-date","last-transaction-date",-996917074),cljs_re_frame.db.generate_random_date()], null)], null),new cljs.core.Keyword(null,"messages","messages",345434482),new cljs.core.PersistentArrayMap(null, 1, ["zero",new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"id","id",-1388402092),"zero",new cljs.core.Keyword(null,"read?","read?",1000202823),true,new cljs.core.Keyword(null,"from","from",1815293044),"Pierre Laplace",new cljs.core.Keyword(null,"title","title",636505583),"A Philosophical Essay on Probabilities",new cljs.core.Keyword(null,"content","content",15833224),"We may regard the present state of the universe as the effect of its past and the cause of its future. An intellect which at a certain moment would know all forces that set nature in motion, and all positions of all items of which nature is composed, if this intellect were also vast enough to submit these data to analysis, it would embrace in a single formula the movements of the greatest bodies of the universe and those of the tiniest atom; for such an intellect nothing would be uncertain and the future just like the past would be present before its eyes.",new cljs.core.Keyword(null,"date","date",-1463434462),"1773-01-01"], null)], null)], null);

//# sourceMappingURL=cljs_re_frame.db.js.map
