name: Bank.Fable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Restore tools
      run: dotnet tool restore
      working-directory: ./Bank/Fable
      
    - name: Restore dotnet dependencies 
      run: dotnet paket restore
      working-directory: ./Bank/Fable
    - name: Restore js dependencies
      run: |
        npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.Awesome }}
        npm install
      working-directory: ./Bank/Fable
    - name: Build
      run: dotnet pack -o build
      working-directory: ./
    - name: Install template
      run: dotnet new -i $(ls ./build/*.* | grep Criipto)
      working-directory: ./
    
    - name: create feliz project from template
      run: |
         mkdir deployment-feliz-source
         cd deployment-feliz-source
         dotnet new CriiptoFelizSample
         npm install
         npm run build
      working-directory: ./
      env:
         WEBPACK_OUT_DIR: ../releases/feliz
    - name: Publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: feliz 
        FOLDER: ./releases # netlify will pick up pushes to this branch and make the build output available as a static site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        MESSAGE: "Build: ({sha}) {msg}"
