name: Bank.Fable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Restore tools
      working-directory: ./Bank.Fable
      run: dotnet tool restore
    - name: Restore dotnet dependencies 
      run: dotnet paket restore
      working-directory: ./Bank.Fable
    - name: Restore js dependencies
      run: npm install
      working-directory: ./Bank.Fable
    - name: Build
      run: npm run build
      working-directory: ./Bank.Fable
      env:
       WEBPACK_OUT_DIR: ./build
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: release 
        FOLDER: build # netlify will pick up pushes to this branch and make the build output available as a static site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        MESSAGE: "Build: ({sha}) {msg}"
