name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dotnet dependencies 
      run: dotnet paket restore 
    - name: Restore js dependencies
      run: npm install
    - name: Build
      run: npm run build
      env:
       WEBPACK_OUT_DIR: ./deploy
